// ---------------------------------------------------------------------------
// contacts
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const Contacts = sequelize.define('contacts', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        name: { type: DataTypes.TEXT },
        email: { type: DataTypes.TEXT },
        company: { type: DataTypes.TEXT },
        role: { type: DataTypes.TEXT },
        group: { type: DataTypes.TEXT },
        phone: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'contacts',
    });

    return Contacts;
};
