// ---------------------------------------------------------------------------
// landed_cost_commissions_mainline
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const LandedCostCommissionsMainline = sequelize.define('landed_cost_commissions_mainline', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        supplierId: { type: DataTypes.TEXT },
        commissionPct: { type: DataTypes.DECIMAL },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'landed_cost_commissions_mainline',
    });

    return LandedCostCommissionsMainline;
};
