// ---------------------------------------------------------------------------
// landed_cost_rates
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const LandedCostRates = sequelize.define('landed_cost_rates', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        module: { type: DataTypes.TEXT },
        freightPct: { type: DataTypes.DECIMAL },
        dutyPct: { type: DataTypes.DECIMAL },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'landed_cost_rates',
    });

    return LandedCostRates;
};
