// ---------------------------------------------------------------------------
// mainline_packing_cartons
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const MainlinePackingCartons = sequelize.define('mainline_packing_cartons', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        bookingId: { type: DataTypes.TEXT, references: { model: 'mainline_bookings', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        ctnNumber: { type: DataTypes.INTEGER },
        legId: { type: DataTypes.TEXT, references: { model: 'mainline_po_legs', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        skuCode: { type: DataTypes.TEXT, references: { model: 'product_skus', key: 'skuCode', deferrable: Deferrable.INITIALLY_DEFERRED } },
        pcsPerCtn: { type: DataTypes.INTEGER },
        unitPrice: { type: DataTypes.DECIMAL },
        totalUsd: { type: DataTypes.DECIMAL },
        netWeightKgs: { type: DataTypes.DECIMAL },
        grossWeightKgs: { type: DataTypes.DECIMAL },
        measureCm: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'mainline_packing_cartons',
    });

    MainlinePackingCartons.associate = (models) => {
        MainlinePackingCartons.belongsTo(models.MainlineBookings, { as: 'bookingId_ref', foreignKey: 'bookingId', targetKey: 'id', constraints: false });
        MainlinePackingCartons.belongsTo(models.MainlinePoLegs, { as: 'legId_ref', foreignKey: 'legId', targetKey: 'id', constraints: false });
        MainlinePackingCartons.belongsTo(models.ProductSkus, { as: 'skuCode_ref', foreignKey: 'skuCode', targetKey: 'skuCode', constraints: false });
    };

    return MainlinePackingCartons;
};
