// ---------------------------------------------------------------------------
// mainline_shipment_legs
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const MainlineShipmentLegs = sequelize.define('mainline_shipment_legs', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        shipmentId: { type: DataTypes.TEXT, references: { model: 'mainline_shipments', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        legId: { type: DataTypes.TEXT, references: { model: 'mainline_po_legs', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        lotNumber: { type: DataTypes.INTEGER },
        expectedQuantity: { type: DataTypes.INTEGER },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'mainline_shipment_legs',
        indexes: [
            { unique: true, fields: ['shipmentId', 'legId'] },
        ],
    });

    MainlineShipmentLegs.associate = (models) => {
        MainlineShipmentLegs.belongsTo(models.MainlineShipments, { as: 'shipmentId_ref', foreignKey: 'shipmentId', targetKey: 'id', constraints: false });
        MainlineShipmentLegs.belongsTo(models.MainlinePoLegs, { as: 'legId_ref', foreignKey: 'legId', targetKey: 'id', constraints: false });
    };

    return MainlineShipmentLegs;
};
