// ---------------------------------------------------------------------------
// mainline_item_receipt_lines
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const MainlineItemReceiptLines = sequelize.define('mainline_item_receipt_lines', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        receiptId: { type: DataTypes.TEXT, allowNull: false, references: { model: 'mainline_item_receipts', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        skuCode: { type: DataTypes.TEXT },
        qty: { type: DataTypes.INTEGER, allowNull: false },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'mainline_item_receipt_lines',
        indexes: [
            { unique: true, fields: ['receiptId', 'skuCode'] },
        ],
    });

    MainlineItemReceiptLines.associate = (models) => {
        MainlineItemReceiptLines.belongsTo(models.MainlineItemReceipts, { as: 'receiptId_ref', foreignKey: 'receiptId', targetKey: 'id', constraints: false });
        MainlineItemReceiptLines.belongsTo(models.ProductSkus, { as: 'skuCode_ref', foreignKey: 'skuCode', targetKey: 'skuCode', constraints: false });
    };

    return MainlineItemReceiptLines;
};
