// ---------------------------------------------------------------------------
// mainline_commercial_invoices
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const MainlineCommercialInvoices = sequelize.define('mainline_commercial_invoices', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        bookingId: { type: DataTypes.TEXT, references: { model: 'mainline_bookings', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        invoiceNumber: { type: DataTypes.TEXT },
        invoiceDate: { type: DataTypes.DATEONLY },
        source: { type: DataTypes.TEXT },
        status: { type: DataTypes.TEXT },
        confirmedAt: { type: DataTypes.DATE },
        fileUrl: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'mainline_commercial_invoices',
        indexes: [
            { unique: true, fields: ['bookingId'] },
        ],
    });

    MainlineCommercialInvoices.associate = (models) => {
        MainlineCommercialInvoices.belongsTo(models.MainlineBookings, { as: 'bookingId_ref', foreignKey: 'bookingId', targetKey: 'id', constraints: false });
    };

    return MainlineCommercialInvoices;
};
