// ---------------------------------------------------------------------------
// mainline_booking_po_legs
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const MainlineBookingPoLegs = sequelize.define('mainline_booking_po_legs', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        bookingId: { type: DataTypes.TEXT, references: { model: 'mainline_bookings', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        legId: { type: DataTypes.TEXT, references: { model: 'mainline_po_legs', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        units: { type: DataTypes.INTEGER },
        cartons: { type: DataTypes.INTEGER },
        weightKg: { type: DataTypes.DECIMAL },
        cbm: { type: DataTypes.DECIMAL },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'mainline_booking_po_legs',
        indexes: [
            { unique: true, fields: ['bookingId', 'legId'] },
        ],
    });

    MainlineBookingPoLegs.associate = (models) => {
        MainlineBookingPoLegs.belongsTo(models.MainlineBookings, { as: 'bookingId_ref', foreignKey: 'bookingId', targetKey: 'id', constraints: false });
        MainlineBookingPoLegs.belongsTo(models.MainlinePoLegs, { as: 'legId_ref', foreignKey: 'legId', targetKey: 'id', constraints: false });
    };

    return MainlineBookingPoLegs;
};
