// ---------------------------------------------------------------------------
// mainline_asns
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const MainlineAsns = sequelize.define('mainline_asns', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        shipmentId: { type: DataTypes.TEXT, references: { model: 'mainline_shipments', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        fileUrl: { type: DataTypes.TEXT },
        status: { type: DataTypes.TEXT },
        generatedAt: { type: DataTypes.DATE },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'mainline_asns',
    });

    MainlineAsns.associate = (models) => {
        MainlineAsns.belongsTo(models.MainlineShipments, { as: 'shipmentId_ref', foreignKey: 'shipmentId', targetKey: 'id', constraints: false });
    };

    return MainlineAsns;
};
