// ---------------------------------------------------------------------------
// mainline_shipments
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const MainlineShipments = sequelize.define('mainline_shipments', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        shipmentNumber: { type: DataTypes.TEXT, allowNull: false },
        bookingId: { type: DataTypes.TEXT, references: { model: 'mainline_bookings', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        facilityId: { type: DataTypes.TEXT, references: { model: 'warehouse_facilities', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        modeId: { type: DataTypes.TEXT, references: { model: 'modes', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        statusId: { type: DataTypes.TEXT, references: { model: 'statuses', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        containerTypeId: { type: DataTypes.TEXT, references: { model: 'container_types', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        polPortId: { type: DataTypes.TEXT, references: { model: 'ports', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        podPortId: { type: DataTypes.TEXT, references: { model: 'ports', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        blNo: { type: DataTypes.TEXT },
        carrierReference: { type: DataTypes.TEXT },
        // CARGO READY (revised) — the forwarder's working date for this consignment.
        // Seeded from the booking's cargoReadyDate at approve, then editable.
        // ⚠️ NOT the same as cargoReceivedDate below: ready = the goods are
        // available, received = the carrier physically has them. Ready is the
        // EARLIER event (it heads the chronology guard), and the two differ on
        // most live rows. Three CRDs exist in total and each has one owner:
        //   mainline_po_legs.crd        — the PO's, from NetSuite custbody46
        //   mainline_bookings.cargoReadyDate — the booked one, the vendor's
        //   THIS                        — the revised one, the forwarder's
        cargoReadyDate: { type: DataTypes.DATEONLY },
        etdPol: { type: DataTypes.DATEONLY },
        etaPod: { type: DataTypes.DATEONLY },
        eDel: { type: DataTypes.DATEONLY },
        cargoReceivedDate: { type: DataTypes.DATEONLY },
        ata: { type: DataTypes.DATEONLY },
        // Free-text operational note, shared by everyone who can see the shipment
        // (vendors included — they are supplier-scoped, not excluded). Single
        // mutable field, so it carries no author or history: a later edit REPLACES
        // what was there.
        notes: { type: DataTypes.TEXT },
        // "Needs attention" flag. Set only by Admin / Logistics Coordinator via the
        // `shipment_flag_priority` permission — deliberately NOT `shipment_update_status`,
        // which Production and the Freight Forwarder also hold.
        priority: { type: DataTypes.BOOLEAN, defaultValue: false },
        netsuiteId: { type: DataTypes.TEXT },
        invoiceValue: { type: DataTypes.DECIMAL },
        duty: { type: DataTypes.DECIMAL },
        freight: { type: DataTypes.DECIMAL },
        courierId: { type: DataTypes.TEXT, references: { model: 'couriers', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        customsEntryNumber: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'mainline_shipments',
        indexes: [
            { unique: true, fields: ['shipmentNumber'] },
        ],
    });

    MainlineShipments.associate = (models) => {
        MainlineShipments.belongsTo(models.MainlineBookings, { as: 'bookingId_ref', foreignKey: 'bookingId', targetKey: 'id', constraints: false });
        MainlineShipments.belongsTo(models.WarehouseFacilities, { as: 'facilityId_ref', foreignKey: 'facilityId', targetKey: 'id', constraints: false });
        MainlineShipments.belongsTo(models.Modes, { as: 'modeId_ref', foreignKey: 'modeId', targetKey: 'id', constraints: false });
        MainlineShipments.belongsTo(models.Statuses, { as: 'statusId_ref', foreignKey: 'statusId', targetKey: 'id', constraints: false });
        MainlineShipments.belongsTo(models.ContainerTypes, { as: 'containerTypeId_ref', foreignKey: 'containerTypeId', targetKey: 'id', constraints: false });
        MainlineShipments.belongsTo(models.Ports, { as: 'polPortId_ref', foreignKey: 'polPortId', targetKey: 'id', constraints: false });
        MainlineShipments.belongsTo(models.Ports, { as: 'podPortId_ref', foreignKey: 'podPortId', targetKey: 'id', constraints: false });
        MainlineShipments.belongsTo(models.Couriers, { as: 'courierId_ref', foreignKey: 'courierId', targetKey: 'id', constraints: false });
    };

    return MainlineShipments;
};
