// ---------------------------------------------------------------------------
// mainline_po_leg_lines
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
//
// ⚠️ NO PRIMARY KEY IN THE DATA. Sequelize requires one, and inventing an
// autoincrement `id` would add a column the table does not have, so `_seq`
// is the key: it is NOT NULL and unique by construction (assigned 0..n-1 on
// every whole-table write). See database/README.md for why these tables have no
// natural key yet.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const MainlinePoLegLines = sequelize.define('mainline_po_leg_lines', {
        id: { type: DataTypes.TEXT },
        legId: { type: DataTypes.TEXT, references: { model: 'mainline_po_legs', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        skuCode: { type: DataTypes.TEXT, references: { model: 'product_skus', key: 'skuCode', deferrable: Deferrable.INITIALLY_DEFERRED } },
        allocatedQty: { type: DataTypes.INTEGER },
        _seq: { type: DataTypes.BIGINT, allowNull: false, primaryKey: true },
    }, {
        tableName: 'mainline_po_leg_lines',
    });

    MainlinePoLegLines.associate = (models) => {
        MainlinePoLegLines.belongsTo(models.MainlinePoLegs, { as: 'legId_ref', foreignKey: 'legId', targetKey: 'id', constraints: false });
        MainlinePoLegLines.belongsTo(models.ProductSkus, { as: 'skuCode_ref', foreignKey: 'skuCode', targetKey: 'skuCode', constraints: false });
    };

    return MainlinePoLegLines;
};
