// ---------------------------------------------------------------------------
// nri_invoice_sources
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
//
// ⚠️ NO PRIMARY KEY IN THE DATA. Sequelize requires one, and inventing an
// autoincrement `id` would add a column the table does not have, so `_seq`
// is the key: it is NOT NULL and unique by construction (assigned 0..n-1 on
// every whole-table write). See database/README.md for why these tables have no
// natural key yet.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const NriInvoiceSources = sequelize.define('nri_invoice_sources', {
        code: { type: DataTypes.TEXT },
        label: { type: DataTypes.TEXT },
        entity: { type: DataTypes.TEXT },
        facilityId: { type: DataTypes.TEXT },
        parser: { type: DataTypes.TEXT },
        uploadEnabled: { type: DataTypes.BOOLEAN },
        note: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false, primaryKey: true },
    }, {
        tableName: 'nri_invoice_sources',
    });

    return NriInvoiceSources;
};
