// ---------------------------------------------------------------------------
// nri_line_overrides
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const NriLineOverrides = sequelize.define('nri_line_overrides', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        invoiceNo: { type: DataTypes.TEXT },
        seq: { type: DataTypes.INTEGER },
        gl: { type: DataTypes.TEXT },
        class: { type: DataTypes.TEXT },
        note: { type: DataTypes.TEXT },
        updatedBy: { type: DataTypes.TEXT },
        updatedAt: { type: DataTypes.DATE },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'nri_line_overrides',
    });

    return NriLineOverrides;
};
