// ---------------------------------------------------------------------------
// nri_order_master
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
//
// ⚠️ NO PRIMARY KEY IN THE DATA. Sequelize requires one, and inventing an
// autoincrement `id` would add a column the table does not have, so `_seq`
// is the key: it is NOT NULL and unique by construction (assigned 0..n-1 on
// every whole-table write). See database/README.md for why these tables have no
// natural key yet.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const NriOrderMaster = sequelize.define('nri_order_master', {
        entity: { type: DataTypes.TEXT },
        orderNo: { type: DataTypes.TEXT },
        ref2: { type: DataTypes.TEXT },
        custCode: { type: DataTypes.TEXT },
        custName: { type: DataTypes.TEXT },
        orderType: { type: DataTypes.TEXT },
        country: { type: DataTypes.TEXT },
        completed: { type: DataTypes.DATEONLY },
        // NetSuite's own sales-channel segment (cseg_tt_salechannel, e.g. "CA - Ecommerce")
        // — set by the NetSuite pull (lib/nriOrderSync.js); null on rows uploaded from a file.
        // Added by scripts/add-nri-order-sync-columns.js.
        salesChannel: { type: DataTypes.TEXT },
        // 'netsuite' (pulled from NetSuite) | null (uploaded file / workbook sheet)
        source: { type: DataTypes.TEXT },
        // NetSuite record type: 'ItemShip' (an order's fulfilment — orderNo = IF…) or
        // 'RtnAuth' (a return — orderNo = RMA…). null on file rows (all ItemShip).
        recordType: { type: DataTypes.TEXT },
        // a second key an invoice line may quote: a Return Authorization's external
        // reference ("RMA #V0NUF99J", its otherrefnum) — the form ecom returns carry
        altRef: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false, primaryKey: true },
    }, {
        tableName: 'nri_order_master',
    });

    return NriOrderMaster;
};
