// ---------------------------------------------------------------------------
// po_masters
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const PoMasters = sequelize.define('po_masters', {
        trnNumber: { type: DataTypes.TEXT, primaryKey: true },
        supplierId: { type: DataTypes.TEXT, references: { model: 'suppliers', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        seasonId: { type: DataTypes.TEXT, references: { model: 'seasons', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        mainShoulder: { type: DataTypes.TEXT },
        netsuiteId: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'po_masters',
    });

    PoMasters.associate = (models) => {
        PoMasters.belongsTo(models.Suppliers, { as: 'supplierId_ref', foreignKey: 'supplierId', targetKey: 'id', constraints: false });
        PoMasters.belongsTo(models.Seasons, { as: 'seasonId_ref', foreignKey: 'seasonId', targetKey: 'id', constraints: false });
    };

    return PoMasters;
};
