// ---------------------------------------------------------------------------
// po_order_lines
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const PoOrderLines = sequelize.define('po_order_lines', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        poNumber: { type: DataTypes.TEXT, references: { model: 'po_orders', key: 'poNumber', deferrable: Deferrable.INITIALLY_DEFERRED } },
        netsuiteLineId: { type: DataTypes.TEXT },
        skuCode: { type: DataTypes.TEXT },
        orderedQty: { type: DataTypes.INTEGER },
        unitPrice: { type: DataTypes.DECIMAL },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'po_order_lines',
        indexes: [
            { unique: true, fields: ['poNumber', 'netsuiteLineId'] },
            { fields: ['poNumber', 'skuCode'] },
        ],
    });

    PoOrderLines.associate = (models) => {
        PoOrderLines.belongsTo(models.PoOrders, { as: 'poNumber_ref', foreignKey: 'poNumber', targetKey: 'poNumber', constraints: false });
        PoOrderLines.belongsTo(models.ProductSkus, { as: 'skuCode_ref', foreignKey: 'skuCode', targetKey: 'skuCode', constraints: false });
    };

    return PoOrderLines;
};
