// ---------------------------------------------------------------------------
// product_skus
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const ProductSkus = sequelize.define('product_skus', {
        skuCode: { type: DataTypes.TEXT, primaryKey: true },
        styleColor: { type: DataTypes.TEXT },
        itemName: { type: DataTypes.TEXT },
        description: { type: DataTypes.TEXT },
        colorway: { type: DataTypes.TEXT },
        size: { type: DataTypes.TEXT },
        htsCode: { type: DataTypes.TEXT },
        unitPrice: { type: DataTypes.DECIMAL },
        upc: { type: DataTypes.TEXT },
        knitWoven: { type: DataTypes.TEXT },
        category: { type: DataTypes.TEXT },
        gender: { type: DataTypes.TEXT },
        composition: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'product_skus',
    });

    return ProductSkus;
};
