// ---------------------------------------------------------------------------
// sms_cartons
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const SmsCartons = sequelize.define('sms_cartons', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        shipmentId: { type: DataTypes.TEXT, allowNull: false, references: { model: 'sms_shipments', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        ctnNumber: { type: DataTypes.INTEGER, allowNull: false },
        netWeightKgs: { type: DataTypes.DECIMAL },
        grossWeightKgs: { type: DataTypes.DECIMAL },
        measureCm: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'sms_cartons',
        indexes: [
            { unique: true, fields: ['shipmentId', 'ctnNumber'] },
        ],
    });

    SmsCartons.associate = (models) => {
        SmsCartons.belongsTo(models.SmsShipments, { as: 'shipmentId_ref', foreignKey: 'shipmentId', targetKey: 'id', constraints: false });
    };

    return SmsCartons;
};
