// ---------------------------------------------------------------------------
// sms_item_receipt_lines
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const SmsItemReceiptLines = sequelize.define('sms_item_receipt_lines', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        receiptId: { type: DataTypes.TEXT, allowNull: false, references: { model: 'sms_item_receipts', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        skuCode: { type: DataTypes.TEXT, references: { model: 'product_skus', key: 'skuCode', deferrable: Deferrable.INITIALLY_DEFERRED } },
        qty: { type: DataTypes.INTEGER, allowNull: false },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'sms_item_receipt_lines',
        indexes: [
            { unique: true, fields: ['receiptId', 'skuCode'] },
        ],
    });

    SmsItemReceiptLines.associate = (models) => {
        SmsItemReceiptLines.belongsTo(models.SmsItemReceipts, { as: 'receiptId_ref', foreignKey: 'receiptId', targetKey: 'id', constraints: false });
        SmsItemReceiptLines.belongsTo(models.ProductSkus, { as: 'skuCode_ref', foreignKey: 'skuCode', targetKey: 'skuCode', constraints: false });
    };

    return SmsItemReceiptLines;
};
