// ---------------------------------------------------------------------------
// sms_pos
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const SmsPos = sequelize.define('sms_pos', {
        poNumber: { type: DataTypes.TEXT, primaryKey: true },
        trnNumber: { type: DataTypes.TEXT },
        supplierId: { type: DataTypes.TEXT, references: { model: 'suppliers', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        seasonId: { type: DataTypes.TEXT, references: { model: 'seasons', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        hod: { type: DataTypes.DATEONLY },
        expectedReceivedDate: { type: DataTypes.DATEONLY },
        shipMethod: { type: DataTypes.TEXT },
        approvalStatus: { type: DataTypes.TEXT },
        facilityId: { type: DataTypes.TEXT, references: { model: 'warehouse_facilities', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        allocationChannelId: { type: DataTypes.TEXT, references: { model: 'allocation_channels', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        netsuiteId: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'sms_pos',
        indexes: [
            { unique: true, fields: ['netsuiteId'] },
        ],
    });

    SmsPos.associate = (models) => {
        SmsPos.belongsTo(models.Suppliers, { as: 'supplierId_ref', foreignKey: 'supplierId', targetKey: 'id', constraints: false });
        SmsPos.belongsTo(models.Seasons, { as: 'seasonId_ref', foreignKey: 'seasonId', targetKey: 'id', constraints: false });
        SmsPos.belongsTo(models.WarehouseFacilities, { as: 'facilityId_ref', foreignKey: 'facilityId', targetKey: 'id', constraints: false });
        SmsPos.belongsTo(models.AllocationChannels, { as: 'allocationChannelId_ref', foreignKey: 'allocationChannelId', targetKey: 'id', constraints: false });
    };

    return SmsPos;
};
