// ---------------------------------------------------------------------------
// sms_shipment_pos
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const SmsShipmentPos = sequelize.define('sms_shipment_pos', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        shipmentId: { type: DataTypes.TEXT, allowNull: false, references: { model: 'sms_shipments', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        poNumber: { type: DataTypes.TEXT, allowNull: false, references: { model: 'sms_pos', key: 'poNumber', deferrable: Deferrable.INITIALLY_DEFERRED } },
        lotNumber: { type: DataTypes.INTEGER, allowNull: false },
        units: { type: DataTypes.INTEGER, allowNull: false },
        cartons: { type: DataTypes.INTEGER },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'sms_shipment_pos',
        indexes: [
            { unique: true, fields: ['poNumber', 'lotNumber'] },
            { unique: true, fields: ['shipmentId', 'poNumber'] },
        ],
    });

    SmsShipmentPos.associate = (models) => {
        SmsShipmentPos.belongsTo(models.SmsShipments, { as: 'shipmentId_ref', foreignKey: 'shipmentId', targetKey: 'id', constraints: false });
        SmsShipmentPos.belongsTo(models.SmsPos, { as: 'poNumber_ref', foreignKey: 'poNumber', targetKey: 'poNumber', constraints: false });
    };

    return SmsShipmentPos;
};
