// ---------------------------------------------------------------------------
// sms_tracking_events
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const SmsTrackingEvents = sequelize.define('sms_tracking_events', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        shipmentId: { type: DataTypes.TEXT, allowNull: false, references: { model: 'sms_shipments', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        eventTime: { type: DataTypes.TEXT, allowNull: false },
        courierCode: { type: DataTypes.TEXT, allowNull: false },
        description: { type: DataTypes.TEXT },
        location: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'sms_tracking_events',
    });

    SmsTrackingEvents.associate = (models) => {
        SmsTrackingEvents.belongsTo(models.SmsShipments, { as: 'shipmentId_ref', foreignKey: 'shipmentId', targetKey: 'id', constraints: false });
    };

    return SmsTrackingEvents;
};
