// ---------------------------------------------------------------------------
// users
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const Users = sequelize.define('users', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        email: { type: DataTypes.TEXT, allowNull: false },
        password: { type: DataTypes.TEXT },
        name: { type: DataTypes.TEXT },
        role: { type: DataTypes.TEXT },
        supplier: { type: DataTypes.TEXT },
        mustChangePassword: { type: DataTypes.BOOLEAN },
        roleId: { type: DataTypes.TEXT, references: { model: 'roles', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        supplierId: { type: DataTypes.TEXT, references: { model: 'suppliers', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'users',
        indexes: [
            { unique: true, fields: ['email'] },
        ],
    });

    Users.associate = (models) => {
        Users.belongsTo(models.Roles, { as: 'roleId_ref', foreignKey: 'roleId', targetKey: 'id', constraints: false });
        Users.belongsTo(models.Suppliers, { as: 'supplierId_ref', foreignKey: 'supplierId', targetKey: 'id', constraints: false });
    };

    return Users;
};
