// ---------------------------------------------------------------------------
// warehouses
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const Warehouses = sequelize.define('warehouses', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        name: { type: DataTypes.TEXT, allowNull: false },
        country: { type: DataTypes.TEXT },
        city: { type: DataTypes.TEXT },
        email: { type: DataTypes.TEXT },
        address: { type: DataTypes.TEXT },
        portOfDischarge: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'warehouses',
        indexes: [
            { unique: true, fields: ['name'] },
        ],
    });

    return Warehouses;
};
