-- GENERATED by backend/db/buildSchema.js from database.dbml + data/**.json.
-- Do not edit by hand: edit database.dbml and re-run `node db/buildSchema.js`.

BEGIN;

-- Whole-file JSON blobs that have no row grain (see DOCUMENT_FILES).
CREATE TABLE IF NOT EXISTS _documents (
    name       text PRIMARY KEY,
    data       json NOT NULL,
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- _seq preserves the ORDER the JSON array had. SQL has no inherent row
-- order, and this codebase depends on the file order in places it states
-- outright: plGenerator takes rows[0] of a carton group, the receipt
-- matcher walks "first still-free IR", and CLAUDE.md records a bug where
-- reversing row order changed 25 of 34 packing summaries. Every read is
-- ORDER BY _seq so that order survives the move.

CREATE TABLE IF NOT EXISTS "asns" (
    "id" text,
    "booking_id" text,
    "booking_number" text,
    "tentree_po_number" text,
    "po_numbers" json,
    "supplier" text,
    "file_url" text,
    "generated_at" timestamptz,
    "status" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "contacts" (
    "id" text,
    "name" text,
    "email" text,
    "company" text,
    "role" text,
    "group" text,
    "phone" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "couriers" (
    "id" text,
    "name" text NOT NULL,
    "provides_cost_invoices" boolean,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "couriers_name_uniq" ON "couriers" ("name");

CREATE TABLE IF NOT EXISTS "freights" (
    _seq bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS "incoterms" (
    "id" text,
    "name" text NOT NULL,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "incoterms_name_uniq" ON "incoterms" ("name");

CREATE TABLE IF NOT EXISTS "modes" (
    "id" text,
    "name" text NOT NULL,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "modes_name_uniq" ON "modes" ("name");

CREATE TABLE IF NOT EXISTS "purchase_orders" (
    "id" text,
    "po_number" text,
    "supplier" text,
    "trn_number" text,
    "season" text,
    "main_shoulder" text,
    "receiving_warehouse" text,
    "coo" text,
    "crd" date,
    "etd" text,
    "etd_pol" text,
    "eta_pod" text,
    "e_del" date,
    "cargo_received_date" text,
    "received_in_netsuite" date,
    "expected_qty" integer,
    "mode" text,
    "incoterm" text,
    "netsuite_id" text,
    "booking_status" text,
    "booking_number" text,
    "type" text,
    "line_items" json,
    "booked_qty" integer,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "roles" (
    "id" text,
    "name" text NOT NULL,
    "description" text,
    "protected" boolean,
    "permissions" json,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "roles_name_uniq" ON "roles" ("name");

CREATE TABLE IF NOT EXISTS "legacy_statuses" (
    "id" text,
    "name" text,
    "color" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "suppliers" (
    "id" text,
    "name" text NOT NULL,
    "country" text,
    "address" text,
    "port_of_loading" text,
    "manufacturer_name" text,
    "manufacturer_address" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "suppliers_name_uniq" ON "suppliers" ("name");

CREATE TABLE IF NOT EXISTS "users" (
    "id" text,
    "email" text NOT NULL,
    "password" text,
    "name" text,
    "role" text,
    "supplier" text,
    "must_change_password" boolean,
    "role_id" text,
    "supplier_id" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "users_email_uniq" ON "users" ("email");

CREATE TABLE IF NOT EXISTS "warehouses" (
    "id" text,
    "name" text NOT NULL,
    "country" text,
    "city" text,
    "email" text,
    "address" text,
    "port_of_discharge" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "warehouses_name_uniq" ON "warehouses" ("name");

CREATE TABLE IF NOT EXISTS "allocation_channels" (
    "id" text,
    "name" text NOT NULL,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "allocation_channels_name_uniq" ON "allocation_channels" ("name");

CREATE TABLE IF NOT EXISTS "container_types" (
    "id" text,
    "name" text NOT NULL,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "container_types_name_uniq" ON "container_types" ("name");

CREATE TABLE IF NOT EXISTS "courier_status_map" (
    "id" text,
    "courier_id" text NOT NULL,
    "courier_code" text NOT NULL,
    "status_id" text NOT NULL,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "courier_status_map_courier_id_courier_code_uniq" ON "courier_status_map" ("courier_id", "courier_code");

CREATE TABLE IF NOT EXISTS "landed_costs" (
    "id" text,
    "module" text,
    "shipment_id" text,
    "po_number" text,
    "invoice_value" numeric,
    "freight_pct" numeric,
    "duty_pct" numeric,
    "freight" numeric,
    "duty" numeric,
    "commission" numeric,
    "posted_by" text,
    "posted_at" timestamptz,
    "netsuite_pushed_at" timestamptz,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "landed_costs_module_shipment_id_po_number_uniq" ON "landed_costs" ("module", "shipment_id", "po_number") NULLS NOT DISTINCT;

CREATE TABLE IF NOT EXISTS "landed_cost_commissions_mainline" (
    "id" text,
    "supplier_id" text,
    "commission_pct" numeric,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "landed_cost_commissions_sms" (
    "id" text,
    "supplier_id" text,
    "commission_pct" numeric,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "landed_cost_rates" (
    "id" text,
    "module" text,
    "freight_pct" numeric,
    "duty_pct" numeric,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "mainline_asns" (
    "id" text,
    "shipment_id" text,
    "file_url" text,
    "status" text,
    "generated_at" timestamptz,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "mainline_bookings" (
    "id" text,
    "booking_number" text NOT NULL,
    "supplier_id" text,
    "incoterm_id" text,
    "courier_id" text,
    "cargo_ready_date" date,
    "booking_status_id" text,
    "submitted_at" timestamptz,
    "approved_at" timestamptz,
    "overbooked" boolean,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "mainline_bookings_booking_number_uniq" ON "mainline_bookings" ("booking_number");

CREATE TABLE IF NOT EXISTS "mainline_booking_po_legs" (
    "id" text,
    "booking_id" text,
    "leg_id" text,
    "units" integer,
    "cartons" integer,
    "weight_kg" numeric,
    "cbm" numeric,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "mainline_booking_po_legs_booking_id_leg_id_uniq" ON "mainline_booking_po_legs" ("booking_id", "leg_id");

CREATE TABLE IF NOT EXISTS "mainline_ci_line_items" (
    "id" text,
    "invoice_id" text,
    "sku_code" text,
    "matched_leg_id" text,
    "qty" integer,
    "weight_kg" numeric,
    "cbm" numeric,
    "match_status" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "mainline_commercial_invoices" (
    "id" text,
    "booking_id" text,
    "invoice_number" text,
    "invoice_date" date,
    "source" text,
    "status" text,
    "confirmed_at" timestamptz,
    "file_url" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "mainline_commercial_invoices_booking_id_uniq" ON "mainline_commercial_invoices" ("booking_id");

CREATE TABLE IF NOT EXISTS "mainline_documents" (
    "id" text,
    "booking_id" text,
    "leg_id" text,
    "doc_type" text,
    "file_url" text,
    "invoice_number" text,
    "generated_at" timestamptz,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "mainline_item_receipts" (
    "id" text,
    "netsuite_ir_id" text,
    "netsuite_ir_tranid" text,
    "po_number" text NOT NULL,
    "receipt_date" date,
    "source" text,
    "matched_shipment_id" text,
    "confirmed_by" text,
    "confirmed_at" timestamptz,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "mainline_item_receipts_netsuite_ir_id_uniq" ON "mainline_item_receipts" ("netsuite_ir_id");

CREATE TABLE IF NOT EXISTS "mainline_item_receipt_lines" (
    "id" text,
    "receipt_id" text NOT NULL,
    "sku_code" text,
    "qty" integer NOT NULL,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "mainline_item_receipt_lines_receipt_id_sku_code_uniq" ON "mainline_item_receipt_lines" ("receipt_id", "sku_code");

CREATE TABLE IF NOT EXISTS "mainline_packing_cartons" (
    "id" text,
    "booking_id" text,
    "ctn_number" integer,
    "leg_id" text,
    "sku_code" text,
    "pcs_per_ctn" integer,
    "unit_price" numeric,
    "total_usd" numeric,
    "net_weight_kgs" numeric,
    "gross_weight_kgs" numeric,
    "measure_cm" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "mainline_po_legs" (
    "id" text,
    "po_number" text,
    "mode_id" text,
    "incoterm_id" text,
    "crd" date,
    "etd_pol" date,
    "e_del" date,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "mainline_po_legs_po_number_mode_id_crd_uniq" ON "mainline_po_legs" ("po_number", "mode_id", "crd");

CREATE TABLE IF NOT EXISTS "mainline_po_leg_lines" (
    "id" text,
    "leg_id" text,
    "sku_code" text,
    "allocated_qty" integer,
    _seq bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS "mainline_receipt_match_rejections" (
    "id" text,
    "receipt_id" text,
    "shipment_id" text,
    "rejected_by" text,
    "rejected_at" timestamptz,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "mainline_receipt_match_rejections_receipt_id_shipment_id_uniq" ON "mainline_receipt_match_rejections" ("receipt_id", "shipment_id");

CREATE TABLE IF NOT EXISTS "mainline_shipments" (
    "id" text,
    "shipment_number" text NOT NULL,
    "booking_id" text,
    "facility_id" text,
    "mode_id" text,
    "status_id" text,
    "container_type_id" text,
    "pol_port_id" text,
    "pod_port_id" text,
    "bl_no" text,
    "carrier_reference" text,
    "etd_pol" date,
    "eta_pod" date,
    "e_del" date,
    "cargo_received_date" date,
    "ata" date,
    "netsuite_id" text,
    "invoice_value" numeric,
    "duty" numeric,
    "freight" numeric,
    "courier_id" text,
    "customs_entry_number" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "mainline_shipments_shipment_number_uniq" ON "mainline_shipments" ("shipment_number");

CREATE TABLE IF NOT EXISTS "mainline_shipment_legs" (
    "id" text,
    "shipment_id" text,
    "leg_id" text,
    "lot_number" integer,
    "expected_quantity" integer,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "mainline_shipment_legs_shipment_id_leg_id_uniq" ON "mainline_shipment_legs" ("shipment_id", "leg_id");

CREATE TABLE IF NOT EXISTS "notify_party" (
    "id" text,
    "name" text NOT NULL,
    "address" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "ports" (
    "id" text,
    "code" text,
    "name" text,
    "country" text,
    "role" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "ports_code_uniq" ON "ports" ("code");

CREATE TABLE IF NOT EXISTS "po_masters" (
    "trn_number" text,
    "supplier_id" text,
    "season_id" text,
    "main_shoulder" text,
    "netsuite_id" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("trn_number")
);

CREATE TABLE IF NOT EXISTS "po_orders" (
    "po_number" text,
    "trn_number" text,
    "facility_id" text,
    "allocation_channel_id" text,
    "coo_country" text,
    "netsuite_id" text,
    "approval_status" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("po_number")
);

CREATE TABLE IF NOT EXISTS "po_order_lines" (
    "id" text,
    "po_number" text,
    "sku_code" text,
    "ordered_qty" integer,
    "unit_price" numeric,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "po_order_lines_po_number_sku_code_uniq" ON "po_order_lines" ("po_number", "sku_code");

CREATE TABLE IF NOT EXISTS "production_schedules" (
    "season_id" text,
    "ontime_by" date,
    "atrisk_by" date,
    _seq bigint NOT NULL,
    PRIMARY KEY ("season_id")
);

CREATE TABLE IF NOT EXISTS "product_skus" (
    "sku_code" text,
    "style_color" text,
    "item_name" text,
    "description" text,
    "colorway" text,
    "size" text,
    "hts_code" text,
    "unit_price" numeric,
    "upc" text,
    "knit_woven" text,
    "category" text,
    "gender" text,
    "composition" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("sku_code")
);

CREATE TABLE IF NOT EXISTS "role_permissions" (
    "role_id" text,
    "permission" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("role_id", "permission")
);

CREATE TABLE IF NOT EXISTS "seasons" (
    "id" text,
    "code" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "seasons_code_uniq" ON "seasons" ("code");

CREATE TABLE IF NOT EXISTS "sms_bookings" (
    "id" text,
    "booking_number" text NOT NULL,
    "supplier_id" text,
    "incoterm_id" text,
    "courier_id" text,
    "mode_id" text,
    "cargo_ready_date" date,
    "booking_status_id" text,
    "submitted_at" timestamptz,
    "approved_at" timestamptz,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "sms_bookings_booking_number_uniq" ON "sms_bookings" ("booking_number");

CREATE TABLE IF NOT EXISTS "sms_booking_pos" (
    "id" text,
    "booking_id" text NOT NULL,
    "po_number" text NOT NULL,
    "lot_number" integer NOT NULL,
    "units" integer NOT NULL,
    "cartons" integer,
    "weight_kg" numeric,
    "cbm" numeric,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "sms_booking_pos_booking_id_po_number_lot_number_uniq" ON "sms_booking_pos" ("booking_id", "po_number", "lot_number");

CREATE TABLE IF NOT EXISTS "sms_cartons" (
    "id" text,
    "shipment_id" text NOT NULL,
    "ctn_number" integer NOT NULL,
    "net_weight_kgs" numeric,
    "gross_weight_kgs" numeric,
    "measure_cm" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "sms_cartons_shipment_id_ctn_number_uniq" ON "sms_cartons" ("shipment_id", "ctn_number");

CREATE TABLE IF NOT EXISTS "sms_documents" (
    "id" text,
    "shipment_id" text NOT NULL,
    "po_number" text,
    "doc_type" text,
    "file_url" text,
    "invoice_number" text,
    "generated_at" timestamptz,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "sms_item_receipts" (
    "id" text,
    "netsuite_ir_id" text,
    "po_number" text NOT NULL,
    "receipt_date" date,
    "source" text,
    "matched_shipment_id" text,
    "confirmed_by" text,
    "confirmed_at" timestamptz,
    "netsuite_ir_tranid" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "sms_item_receipts_netsuite_ir_id_uniq" ON "sms_item_receipts" ("netsuite_ir_id");

CREATE TABLE IF NOT EXISTS "sms_item_receipt_lines" (
    "id" text,
    "receipt_id" text NOT NULL,
    "sku_code" text,
    "qty" integer NOT NULL,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "sms_item_receipt_lines_receipt_id_sku_code_uniq" ON "sms_item_receipt_lines" ("receipt_id", "sku_code");

CREATE TABLE IF NOT EXISTS "sms_packing_cartons" (
    "id" text,
    "shipment_id" text NOT NULL,
    "po_number" text NOT NULL,
    "ctn_number" integer,
    "sku_code" text,
    "pcs_per_ctn" integer,
    "unit_price" numeric,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "sms_packing_cartons_shipment_id_ctn_number_sku_code_uniq" ON "sms_packing_cartons" ("shipment_id", "ctn_number", "sku_code");

CREATE TABLE IF NOT EXISTS "sms_pos" (
    "po_number" text,
    "trn_number" text,
    "supplier_id" text,
    "season_id" text,
    "hod" date,
    "expected_received_date" date,
    "ship_method" text,
    "approval_status" text,
    "facility_id" text,
    "allocation_channel_id" text,
    "netsuite_id" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("po_number")
);
CREATE UNIQUE INDEX IF NOT EXISTS "sms_pos_netsuite_id_uniq" ON "sms_pos" ("netsuite_id");

CREATE TABLE IF NOT EXISTS "sms_po_lines" (
    "id" text,
    "po_number" text NOT NULL,
    "sku_code" text,
    "ordered_qty" integer,
    "unit_price" numeric,
    "netsuite_line_id" text,
    _seq bigint NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS "sms_po_lines_po_number_netsuite_line_id_uniq" ON "sms_po_lines" ("po_number", "netsuite_line_id");
CREATE INDEX IF NOT EXISTS "sms_po_lines_po_number_sku_code_idx" ON "sms_po_lines" ("po_number", "sku_code");

CREATE TABLE IF NOT EXISTS "sms_receipt_match_rejections" (
    "id" text,
    "receipt_id" text NOT NULL,
    "shipment_id" text NOT NULL,
    "rejected_by" text,
    "rejected_at" timestamptz,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "sms_receipt_match_rejections_receipt_id_shipment_id_uniq" ON "sms_receipt_match_rejections" ("receipt_id", "shipment_id");

CREATE TABLE IF NOT EXISTS "sms_shipments" (
    "id" text,
    "courier_id" text NOT NULL,
    "tracking_number" text,
    "ship_date" date,
    "facility_id" text,
    "manual_status_id" text,
    "created_by" text,
    "created_at" timestamptz,
    "booking_id" text,
    "customs_entry_number" text,
    "duty" numeric,
    "freight" numeric,
    "mode_id" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "sms_shipments_tracking_number_uniq" ON "sms_shipments" ("tracking_number");

CREATE TABLE IF NOT EXISTS "sms_shipment_pos" (
    "id" text,
    "shipment_id" text NOT NULL,
    "po_number" text NOT NULL,
    "lot_number" integer NOT NULL,
    "units" integer NOT NULL,
    "cartons" integer,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "sms_shipment_pos_po_number_lot_number_uniq" ON "sms_shipment_pos" ("po_number", "lot_number");
CREATE UNIQUE INDEX IF NOT EXISTS "sms_shipment_pos_shipment_id_po_number_uniq" ON "sms_shipment_pos" ("shipment_id", "po_number");

CREATE TABLE IF NOT EXISTS "sms_tracking_events" (
    "id" text,
    "shipment_id" text NOT NULL,
    "event_time" text NOT NULL,
    "courier_code" text NOT NULL,
    "description" text,
    "location" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "statuses" (
    "id" text,
    "name" text NOT NULL,
    "module" text,
    "category" text,
    "color" text,
    "sort_order" integer,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "statuses_module_name_uniq" ON "statuses" ("module", "name");

CREATE TABLE IF NOT EXISTS "transit_time_standards" (
    "id" text,
    "mode_id" text NOT NULL,
    "segment" text NOT NULL,
    "days" integer NOT NULL,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "transit_time_standards_mode_id_segment_uniq" ON "transit_time_standards" ("mode_id", "segment");

CREATE TABLE IF NOT EXISTS "warehouse_facilities" (
    "id" text,
    "name" text NOT NULL,
    "country" text,
    "city" text,
    "port_of_discharge" text,
    "address" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "warehouse_facilities_name_uniq" ON "warehouse_facilities" ("name");

CREATE TABLE IF NOT EXISTS "nri_charge_codes" (
    "id" text,
    "service" text,
    "service_raw" text,
    "gl" integer,
    "gl_desc" text,
    "class_us" text,
    "class_ca" text,
    "note" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "nri_invoices" (
    _seq bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS "nri_invoice_lines" (
    _seq bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS "nri_invoice_sources" (
    "code" text,
    "label" text,
    "entity" text,
    "facility_id" text,
    "parser" text,
    "upload_enabled" boolean,
    "note" text,
    _seq bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS "nri_line_overrides" (
    "id" text,
    "invoice_no" text,
    "seq" integer,
    "gl" text,
    "class" text,
    "note" text,
    "updated_by" text,
    "updated_at" timestamptz,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "nri_order_master" (
    "entity" text,
    "orderNo" text,
    "ref2" text,
    "custCode" text,
    "custName" text,
    "orderType" text,
    "country" text,
    "completed" date,
    _seq bigint NOT NULL
);

CREATE TABLE IF NOT EXISTS "nri_rate_card" (
    "id" text,
    "entity" text,
    "service" text,
    "basis" text,
    "fixed" numeric,
    "rate" numeric,
    "uom" text,
    "tiers" json,
    "monthly_minimum" numeric,
    "effective_from" date,
    "effective_to" date,
    "source" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "eom_tasks" (
    "id" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "bookings" (
    "id" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "shipments" (
    "id" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "history" (
    "id" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "history_bookings" (
    "id" text,
    _seq bigint NOT NULL,
    PRIMARY KEY ("id")
);

-- Foreign keys are DEFERRABLE INITIALLY DEFERRED: the app writes whole tables
-- one at a time (BaseModel.write), so a delete that spans a parent and its
-- children is momentarily inconsistent mid-request and only has to balance at
-- COMMIT. db/txContext.js wraps each HTTP request in one transaction so that
-- is exactly when it is checked.
ALTER TABLE "users" ADD CONSTRAINT "users_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "users" ADD CONSTRAINT "users_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "courier_status_map" ADD CONSTRAINT "courier_status_map_status_id_fkey" FOREIGN KEY ("status_id") REFERENCES "statuses" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "landed_costs" ADD CONSTRAINT "landed_costs_posted_by_fkey" FOREIGN KEY ("posted_by") REFERENCES "users" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_asns" ADD CONSTRAINT "mainline_asns_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "mainline_shipments" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_bookings" ADD CONSTRAINT "mainline_bookings_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_bookings" ADD CONSTRAINT "mainline_bookings_incoterm_id_fkey" FOREIGN KEY ("incoterm_id") REFERENCES "incoterms" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_bookings" ADD CONSTRAINT "mainline_bookings_courier_id_fkey" FOREIGN KEY ("courier_id") REFERENCES "couriers" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_bookings" ADD CONSTRAINT "mainline_bookings_booking_status_id_fkey" FOREIGN KEY ("booking_status_id") REFERENCES "statuses" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_booking_po_legs" ADD CONSTRAINT "mainline_booking_po_legs_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "mainline_bookings" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_booking_po_legs" ADD CONSTRAINT "mainline_booking_po_legs_leg_id_fkey" FOREIGN KEY ("leg_id") REFERENCES "mainline_po_legs" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_ci_line_items" ADD CONSTRAINT "mainline_ci_line_items_invoice_id_fkey" FOREIGN KEY ("invoice_id") REFERENCES "mainline_commercial_invoices" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_ci_line_items" ADD CONSTRAINT "mainline_ci_line_items_sku_code_fkey" FOREIGN KEY ("sku_code") REFERENCES "product_skus" ("sku_code") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_ci_line_items" ADD CONSTRAINT "mainline_ci_line_items_matched_leg_id_fkey" FOREIGN KEY ("matched_leg_id") REFERENCES "mainline_po_legs" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_commercial_invoices" ADD CONSTRAINT "mainline_commercial_invoices_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "mainline_bookings" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_item_receipts" ADD CONSTRAINT "mainline_item_receipts_po_number_fkey" FOREIGN KEY ("po_number") REFERENCES "po_orders" ("po_number") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_item_receipts" ADD CONSTRAINT "mainline_item_receipts_matched_shipment_id_fkey" FOREIGN KEY ("matched_shipment_id") REFERENCES "mainline_shipments" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_item_receipt_lines" ADD CONSTRAINT "mainline_item_receipt_lines_receipt_id_fkey" FOREIGN KEY ("receipt_id") REFERENCES "mainline_item_receipts" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_packing_cartons" ADD CONSTRAINT "mainline_packing_cartons_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "mainline_bookings" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_packing_cartons" ADD CONSTRAINT "mainline_packing_cartons_leg_id_fkey" FOREIGN KEY ("leg_id") REFERENCES "mainline_po_legs" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_packing_cartons" ADD CONSTRAINT "mainline_packing_cartons_sku_code_fkey" FOREIGN KEY ("sku_code") REFERENCES "product_skus" ("sku_code") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_po_legs" ADD CONSTRAINT "mainline_po_legs_po_number_fkey" FOREIGN KEY ("po_number") REFERENCES "po_orders" ("po_number") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_po_legs" ADD CONSTRAINT "mainline_po_legs_mode_id_fkey" FOREIGN KEY ("mode_id") REFERENCES "modes" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_po_legs" ADD CONSTRAINT "mainline_po_legs_incoterm_id_fkey" FOREIGN KEY ("incoterm_id") REFERENCES "incoterms" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_po_leg_lines" ADD CONSTRAINT "mainline_po_leg_lines_leg_id_fkey" FOREIGN KEY ("leg_id") REFERENCES "mainline_po_legs" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_po_leg_lines" ADD CONSTRAINT "mainline_po_leg_lines_sku_code_fkey" FOREIGN KEY ("sku_code") REFERENCES "product_skus" ("sku_code") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_receipt_match_rejections" ADD CONSTRAINT "mainline_receipt_match_rejections_receipt_id_fkey" FOREIGN KEY ("receipt_id") REFERENCES "mainline_item_receipts" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_receipt_match_rejections" ADD CONSTRAINT "mainline_receipt_match_rejections_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "mainline_shipments" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_shipments" ADD CONSTRAINT "mainline_shipments_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "mainline_bookings" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_shipments" ADD CONSTRAINT "mainline_shipments_facility_id_fkey" FOREIGN KEY ("facility_id") REFERENCES "warehouse_facilities" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_shipments" ADD CONSTRAINT "mainline_shipments_mode_id_fkey" FOREIGN KEY ("mode_id") REFERENCES "modes" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_shipments" ADD CONSTRAINT "mainline_shipments_status_id_fkey" FOREIGN KEY ("status_id") REFERENCES "statuses" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_shipments" ADD CONSTRAINT "mainline_shipments_container_type_id_fkey" FOREIGN KEY ("container_type_id") REFERENCES "container_types" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_shipments" ADD CONSTRAINT "mainline_shipments_pol_port_id_fkey" FOREIGN KEY ("pol_port_id") REFERENCES "ports" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_shipments" ADD CONSTRAINT "mainline_shipments_pod_port_id_fkey" FOREIGN KEY ("pod_port_id") REFERENCES "ports" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_shipments" ADD CONSTRAINT "mainline_shipments_courier_id_fkey" FOREIGN KEY ("courier_id") REFERENCES "couriers" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_shipment_legs" ADD CONSTRAINT "mainline_shipment_legs_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "mainline_shipments" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "mainline_shipment_legs" ADD CONSTRAINT "mainline_shipment_legs_leg_id_fkey" FOREIGN KEY ("leg_id") REFERENCES "mainline_po_legs" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "po_masters" ADD CONSTRAINT "po_masters_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "po_masters" ADD CONSTRAINT "po_masters_season_id_fkey" FOREIGN KEY ("season_id") REFERENCES "seasons" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "po_orders" ADD CONSTRAINT "po_orders_trn_number_fkey" FOREIGN KEY ("trn_number") REFERENCES "po_masters" ("trn_number") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "po_orders" ADD CONSTRAINT "po_orders_facility_id_fkey" FOREIGN KEY ("facility_id") REFERENCES "warehouse_facilities" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "po_orders" ADD CONSTRAINT "po_orders_allocation_channel_id_fkey" FOREIGN KEY ("allocation_channel_id") REFERENCES "allocation_channels" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "po_order_lines" ADD CONSTRAINT "po_order_lines_po_number_fkey" FOREIGN KEY ("po_number") REFERENCES "po_orders" ("po_number") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "production_schedules" ADD CONSTRAINT "production_schedules_season_id_fkey" FOREIGN KEY ("season_id") REFERENCES "seasons" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_id_fkey" FOREIGN KEY ("role_id") REFERENCES "roles" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_bookings" ADD CONSTRAINT "sms_bookings_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_bookings" ADD CONSTRAINT "sms_bookings_incoterm_id_fkey" FOREIGN KEY ("incoterm_id") REFERENCES "incoterms" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_bookings" ADD CONSTRAINT "sms_bookings_courier_id_fkey" FOREIGN KEY ("courier_id") REFERENCES "couriers" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_bookings" ADD CONSTRAINT "sms_bookings_mode_id_fkey" FOREIGN KEY ("mode_id") REFERENCES "modes" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_bookings" ADD CONSTRAINT "sms_bookings_booking_status_id_fkey" FOREIGN KEY ("booking_status_id") REFERENCES "statuses" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_booking_pos" ADD CONSTRAINT "sms_booking_pos_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "sms_bookings" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_booking_pos" ADD CONSTRAINT "sms_booking_pos_po_number_fkey" FOREIGN KEY ("po_number") REFERENCES "sms_pos" ("po_number") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_cartons" ADD CONSTRAINT "sms_cartons_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "sms_shipments" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_documents" ADD CONSTRAINT "sms_documents_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "sms_shipments" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_documents" ADD CONSTRAINT "sms_documents_po_number_fkey" FOREIGN KEY ("po_number") REFERENCES "sms_pos" ("po_number") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_item_receipts" ADD CONSTRAINT "sms_item_receipts_po_number_fkey" FOREIGN KEY ("po_number") REFERENCES "sms_pos" ("po_number") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_item_receipts" ADD CONSTRAINT "sms_item_receipts_matched_shipment_id_fkey" FOREIGN KEY ("matched_shipment_id") REFERENCES "sms_shipments" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_item_receipt_lines" ADD CONSTRAINT "sms_item_receipt_lines_receipt_id_fkey" FOREIGN KEY ("receipt_id") REFERENCES "sms_item_receipts" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_item_receipt_lines" ADD CONSTRAINT "sms_item_receipt_lines_sku_code_fkey" FOREIGN KEY ("sku_code") REFERENCES "product_skus" ("sku_code") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_packing_cartons" ADD CONSTRAINT "sms_packing_cartons_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "sms_shipments" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_packing_cartons" ADD CONSTRAINT "sms_packing_cartons_po_number_fkey" FOREIGN KEY ("po_number") REFERENCES "sms_pos" ("po_number") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_packing_cartons" ADD CONSTRAINT "sms_packing_cartons_sku_code_fkey" FOREIGN KEY ("sku_code") REFERENCES "product_skus" ("sku_code") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_pos" ADD CONSTRAINT "sms_pos_supplier_id_fkey" FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_pos" ADD CONSTRAINT "sms_pos_season_id_fkey" FOREIGN KEY ("season_id") REFERENCES "seasons" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_pos" ADD CONSTRAINT "sms_pos_facility_id_fkey" FOREIGN KEY ("facility_id") REFERENCES "warehouse_facilities" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_pos" ADD CONSTRAINT "sms_pos_allocation_channel_id_fkey" FOREIGN KEY ("allocation_channel_id") REFERENCES "allocation_channels" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_po_lines" ADD CONSTRAINT "sms_po_lines_po_number_fkey" FOREIGN KEY ("po_number") REFERENCES "sms_pos" ("po_number") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_po_lines" ADD CONSTRAINT "sms_po_lines_sku_code_fkey" FOREIGN KEY ("sku_code") REFERENCES "product_skus" ("sku_code") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_receipt_match_rejections" ADD CONSTRAINT "sms_receipt_match_rejections_receipt_id_fkey" FOREIGN KEY ("receipt_id") REFERENCES "sms_item_receipts" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_receipt_match_rejections" ADD CONSTRAINT "sms_receipt_match_rejections_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "sms_shipments" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_shipments" ADD CONSTRAINT "sms_shipments_mode_id_fkey" FOREIGN KEY ("mode_id") REFERENCES "modes" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_shipments" ADD CONSTRAINT "sms_shipments_facility_id_fkey" FOREIGN KEY ("facility_id") REFERENCES "warehouse_facilities" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_shipments" ADD CONSTRAINT "sms_shipments_manual_status_id_fkey" FOREIGN KEY ("manual_status_id") REFERENCES "statuses" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_shipments" ADD CONSTRAINT "sms_shipments_booking_id_fkey" FOREIGN KEY ("booking_id") REFERENCES "sms_bookings" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_shipment_pos" ADD CONSTRAINT "sms_shipment_pos_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "sms_shipments" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_shipment_pos" ADD CONSTRAINT "sms_shipment_pos_po_number_fkey" FOREIGN KEY ("po_number") REFERENCES "sms_pos" ("po_number") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "sms_tracking_events" ADD CONSTRAINT "sms_tracking_events_shipment_id_fkey" FOREIGN KEY ("shipment_id") REFERENCES "sms_shipments" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "transit_time_standards" ADD CONSTRAINT "transit_time_standards_mode_id_fkey" FOREIGN KEY ("mode_id") REFERENCES "modes" ("id") DEFERRABLE INITIALLY DEFERRED;

COMMIT;
