// ---------------------------------------------------------------------------
// couriers
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const Couriers = sequelize.define('couriers', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        name: { type: DataTypes.TEXT, allowNull: false },
        providesCostInvoices: { type: DataTypes.BOOLEAN },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'couriers',
        indexes: [
            { unique: true, fields: ['name'] },
        ],
    });

    return Couriers;
};
