// ---------------------------------------------------------------------------
// courier_status_map
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const CourierStatusMap = sequelize.define('courier_status_map', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        courierId: { type: DataTypes.TEXT, allowNull: false },
        courierCode: { type: DataTypes.TEXT, allowNull: false },
        statusId: { type: DataTypes.TEXT, allowNull: false, references: { model: 'statuses', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'courier_status_map',
        indexes: [
            { unique: true, fields: ['courierId', 'courierCode'] },
        ],
    });

    CourierStatusMap.associate = (models) => {
        CourierStatusMap.belongsTo(models.Statuses, { as: 'statusId_ref', foreignKey: 'statusId', targetKey: 'id', constraints: false });
    };

    return CourierStatusMap;
};
