// ---------------------------------------------------------------------------
// landed_costs
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const LandedCosts = sequelize.define('landed_costs', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        module: { type: DataTypes.TEXT },
        shipmentId: { type: DataTypes.TEXT },
        poNumber: { type: DataTypes.TEXT },
        invoiceValue: { type: DataTypes.DECIMAL },
        freightPct: { type: DataTypes.DECIMAL },
        dutyPct: { type: DataTypes.DECIMAL },
        freight: { type: DataTypes.DECIMAL },
        duty: { type: DataTypes.DECIMAL },
        commission: { type: DataTypes.DECIMAL },
        postedBy: { type: DataTypes.TEXT, references: { model: 'users', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        postedAt: { type: DataTypes.DATE },
        netsuitePushedAt: { type: DataTypes.DATE },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'landed_costs',
        indexes: [
            { unique: true, fields: ['module', 'shipmentId', 'poNumber'] },   // NULLS NOT DISTINCT in the DDL — Sequelize cannot express it
        ],
    });

    LandedCosts.associate = (models) => {
        LandedCosts.belongsTo(models.Users, { as: 'postedBy_ref', foreignKey: 'postedBy', targetKey: 'id', constraints: false });
    };

    return LandedCosts;
};
