// ---------------------------------------------------------------------------
// legacy_statuses
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const LegacyStatuses = sequelize.define('legacy_statuses', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        name: { type: DataTypes.TEXT },
        color: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'legacy_statuses',
    });

    return LegacyStatuses;
};
