// ---------------------------------------------------------------------------
// mainline_item_receipts
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const MainlineItemReceipts = sequelize.define('mainline_item_receipts', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        netsuiteIrId: { type: DataTypes.TEXT },
        netsuiteIrTranid: { type: DataTypes.TEXT },
        poNumber: { type: DataTypes.TEXT, allowNull: false, references: { model: 'po_orders', key: 'poNumber', deferrable: Deferrable.INITIALLY_DEFERRED } },
        receiptDate: { type: DataTypes.DATEONLY },
        source: { type: DataTypes.TEXT },
        matchedShipmentId: { type: DataTypes.TEXT, references: { model: 'mainline_shipments', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        confirmedBy: { type: DataTypes.TEXT },
        confirmedAt: { type: DataTypes.DATE },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'mainline_item_receipts',
        indexes: [
            { unique: true, fields: ['netsuiteIrId'] },
        ],
    });

    MainlineItemReceipts.associate = (models) => {
        MainlineItemReceipts.belongsTo(models.PoOrders, { as: 'poNumber_ref', foreignKey: 'poNumber', targetKey: 'poNumber', constraints: false });
        MainlineItemReceipts.belongsTo(models.MainlineShipments, { as: 'matchedShipmentId_ref', foreignKey: 'matchedShipmentId', targetKey: 'id', constraints: false });
    };

    return MainlineItemReceipts;
};
