// ---------------------------------------------------------------------------
// mainline_documents
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const MainlineDocuments = sequelize.define('mainline_documents', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        bookingId: { type: DataTypes.TEXT },
        legId: { type: DataTypes.TEXT },
        docType: { type: DataTypes.TEXT },
        fileUrl: { type: DataTypes.TEXT },
        invoiceNumber: { type: DataTypes.TEXT },
        generatedAt: { type: DataTypes.DATE },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'mainline_documents',
    });

    return MainlineDocuments;
};
