// ---------------------------------------------------------------------------
// mainline_po_legs
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const MainlinePoLegs = sequelize.define('mainline_po_legs', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        poNumber: { type: DataTypes.TEXT, references: { model: 'po_orders', key: 'poNumber', deferrable: Deferrable.INITIALLY_DEFERRED } },
        modeId: { type: DataTypes.TEXT, references: { model: 'modes', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        incotermId: { type: DataTypes.TEXT, references: { model: 'incoterms', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        crd: { type: DataTypes.DATEONLY },
        etdPol: { type: DataTypes.DATEONLY },
        eDel: { type: DataTypes.DATEONLY },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'mainline_po_legs',
        indexes: [
            { unique: true, fields: ['poNumber', 'modeId', 'crd'] },
        ],
    });

    MainlinePoLegs.associate = (models) => {
        MainlinePoLegs.belongsTo(models.PoOrders, { as: 'poNumber_ref', foreignKey: 'poNumber', targetKey: 'poNumber', constraints: false });
        MainlinePoLegs.belongsTo(models.Modes, { as: 'modeId_ref', foreignKey: 'modeId', targetKey: 'id', constraints: false });
        MainlinePoLegs.belongsTo(models.Incoterms, { as: 'incotermId_ref', foreignKey: 'incotermId', targetKey: 'id', constraints: false });
    };

    return MainlinePoLegs;
};
