// ---------------------------------------------------------------------------
// mainline_bookings
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const MainlineBookings = sequelize.define('mainline_bookings', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        bookingNumber: { type: DataTypes.TEXT, allowNull: false },
        supplierId: { type: DataTypes.TEXT, references: { model: 'suppliers', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        incotermId: { type: DataTypes.TEXT, references: { model: 'incoterms', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        courierId: { type: DataTypes.TEXT, references: { model: 'couriers', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        cargoReadyDate: { type: DataTypes.DATEONLY },
        bookingStatusId: { type: DataTypes.TEXT, references: { model: 'statuses', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        submittedAt: { type: DataTypes.DATE },
        approvedAt: { type: DataTypes.DATE },
        overbooked: { type: DataTypes.BOOLEAN },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'mainline_bookings',
        indexes: [
            { unique: true, fields: ['bookingNumber'] },
        ],
    });

    MainlineBookings.associate = (models) => {
        MainlineBookings.belongsTo(models.Suppliers, { as: 'supplierId_ref', foreignKey: 'supplierId', targetKey: 'id', constraints: false });
        MainlineBookings.belongsTo(models.Incoterms, { as: 'incotermId_ref', foreignKey: 'incotermId', targetKey: 'id', constraints: false });
        MainlineBookings.belongsTo(models.Couriers, { as: 'courierId_ref', foreignKey: 'courierId', targetKey: 'id', constraints: false });
        MainlineBookings.belongsTo(models.Statuses, { as: 'bookingStatusId_ref', foreignKey: 'bookingStatusId', targetKey: 'id', constraints: false });
    };

    return MainlineBookings;
};
