// ---------------------------------------------------------------------------
// mainline_receipt_match_rejections
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const MainlineReceiptMatchRejections = sequelize.define('mainline_receipt_match_rejections', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        receiptId: { type: DataTypes.TEXT, references: { model: 'mainline_item_receipts', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        shipmentId: { type: DataTypes.TEXT, references: { model: 'mainline_shipments', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        rejectedBy: { type: DataTypes.TEXT },
        rejectedAt: { type: DataTypes.DATE },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'mainline_receipt_match_rejections',
        indexes: [
            { unique: true, fields: ['receiptId', 'shipmentId'] },
        ],
    });

    MainlineReceiptMatchRejections.associate = (models) => {
        MainlineReceiptMatchRejections.belongsTo(models.MainlineItemReceipts, { as: 'receiptId_ref', foreignKey: 'receiptId', targetKey: 'id', constraints: false });
        MainlineReceiptMatchRejections.belongsTo(models.MainlineShipments, { as: 'shipmentId_ref', foreignKey: 'shipmentId', targetKey: 'id', constraints: false });
    };

    return MainlineReceiptMatchRejections;
};
