// ---------------------------------------------------------------------------
// nri_charge_codes
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const NriChargeCodes = sequelize.define('nri_charge_codes', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        service: { type: DataTypes.TEXT },
        serviceRaw: { type: DataTypes.TEXT },
        gl: { type: DataTypes.INTEGER },
        glDesc: { type: DataTypes.TEXT },
        classUs: { type: DataTypes.TEXT },
        classCa: { type: DataTypes.TEXT },
        note: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'nri_charge_codes',
    });

    return NriChargeCodes;
};
