// ---------------------------------------------------------------------------
// nri_rate_card
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const NriRateCard = sequelize.define('nri_rate_card', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        entity: { type: DataTypes.TEXT },
        service: { type: DataTypes.TEXT },
        basis: { type: DataTypes.TEXT },
        fixed: { type: DataTypes.DECIMAL },
        rate: { type: DataTypes.DECIMAL },
        uom: { type: DataTypes.TEXT },
        tiers: { type: DataTypes.JSON },
        monthlyMinimum: { type: DataTypes.DECIMAL },
        effectiveFrom: { type: DataTypes.DATEONLY },
        effectiveTo: { type: DataTypes.DATEONLY },
        source: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'nri_rate_card',
    });

    return NriRateCard;
};
