// ---------------------------------------------------------------------------
// po_orders
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const PoOrders = sequelize.define('po_orders', {
        poNumber: { type: DataTypes.TEXT, primaryKey: true },
        trnNumber: { type: DataTypes.TEXT, references: { model: 'po_masters', key: 'trnNumber', deferrable: Deferrable.INITIALLY_DEFERRED } },
        facilityId: { type: DataTypes.TEXT, references: { model: 'warehouse_facilities', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        allocationChannelId: { type: DataTypes.TEXT, references: { model: 'allocation_channels', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        cooCountry: { type: DataTypes.TEXT },
        netsuiteId: { type: DataTypes.TEXT },
        approvalStatus: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'po_orders',
    });

    PoOrders.associate = (models) => {
        PoOrders.belongsTo(models.PoMasters, { as: 'trnNumber_ref', foreignKey: 'trnNumber', targetKey: 'trnNumber', constraints: false });
        PoOrders.belongsTo(models.WarehouseFacilities, { as: 'facilityId_ref', foreignKey: 'facilityId', targetKey: 'id', constraints: false });
        PoOrders.belongsTo(models.AllocationChannels, { as: 'allocationChannelId_ref', foreignKey: 'allocationChannelId', targetKey: 'id', constraints: false });
    };

    return PoOrders;
};
