// ---------------------------------------------------------------------------
// ports
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const Ports = sequelize.define('ports', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        code: { type: DataTypes.TEXT },
        name: { type: DataTypes.TEXT },
        country: { type: DataTypes.TEXT },
        role: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'ports',
        indexes: [
            { unique: true, fields: ['code'] },
        ],
    });

    return Ports;
};
