// ---------------------------------------------------------------------------
// production_schedules
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const ProductionSchedules = sequelize.define('production_schedules', {
        seasonId: { type: DataTypes.TEXT, primaryKey: true, references: { model: 'seasons', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        ontimeBy: { type: DataTypes.DATEONLY },
        atriskBy: { type: DataTypes.DATEONLY },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'production_schedules',
    });

    ProductionSchedules.associate = (models) => {
        ProductionSchedules.belongsTo(models.Seasons, { as: 'seasonId_ref', foreignKey: 'seasonId', targetKey: 'id', constraints: false });
    };

    return ProductionSchedules;
};
