// ---------------------------------------------------------------------------
// roles
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const Roles = sequelize.define('roles', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        name: { type: DataTypes.TEXT, allowNull: false },
        description: { type: DataTypes.TEXT },
        protected: { type: DataTypes.BOOLEAN },
        permissions: { type: DataTypes.JSON },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'roles',
        indexes: [
            { unique: true, fields: ['name'] },
        ],
    });

    return Roles;
};
