// ---------------------------------------------------------------------------
// seasons
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const Seasons = sequelize.define('seasons', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        code: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'seasons',
        indexes: [
            { unique: true, fields: ['code'] },
        ],
    });

    return Seasons;
};
