// ---------------------------------------------------------------------------
// sms_booking_pos
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const SmsBookingPos = sequelize.define('sms_booking_pos', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        bookingId: { type: DataTypes.TEXT, allowNull: false, references: { model: 'sms_bookings', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        poNumber: { type: DataTypes.TEXT, allowNull: false, references: { model: 'sms_pos', key: 'poNumber', deferrable: Deferrable.INITIALLY_DEFERRED } },
        lotNumber: { type: DataTypes.INTEGER, allowNull: false },
        units: { type: DataTypes.INTEGER, allowNull: false },
        cartons: { type: DataTypes.INTEGER },
        weightKg: { type: DataTypes.DECIMAL },
        cbm: { type: DataTypes.DECIMAL },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'sms_booking_pos',
        indexes: [
            { unique: true, fields: ['bookingId', 'poNumber', 'lotNumber'] },
        ],
    });

    SmsBookingPos.associate = (models) => {
        SmsBookingPos.belongsTo(models.SmsBookings, { as: 'bookingId_ref', foreignKey: 'bookingId', targetKey: 'id', constraints: false });
        SmsBookingPos.belongsTo(models.SmsPos, { as: 'poNumber_ref', foreignKey: 'poNumber', targetKey: 'poNumber', constraints: false });
    };

    return SmsBookingPos;
};
