// ---------------------------------------------------------------------------
// sms_documents
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const SmsDocuments = sequelize.define('sms_documents', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        shipmentId: { type: DataTypes.TEXT, allowNull: false, references: { model: 'sms_shipments', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        poNumber: { type: DataTypes.TEXT, references: { model: 'sms_pos', key: 'poNumber', deferrable: Deferrable.INITIALLY_DEFERRED } },
        docType: { type: DataTypes.TEXT },
        fileUrl: { type: DataTypes.TEXT },
        invoiceNumber: { type: DataTypes.TEXT },
        generatedAt: { type: DataTypes.DATE },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'sms_documents',
    });

    SmsDocuments.associate = (models) => {
        SmsDocuments.belongsTo(models.SmsShipments, { as: 'shipmentId_ref', foreignKey: 'shipmentId', targetKey: 'id', constraints: false });
        SmsDocuments.belongsTo(models.SmsPos, { as: 'poNumber_ref', foreignKey: 'poNumber', targetKey: 'poNumber', constraints: false });
    };

    return SmsDocuments;
};
