// ---------------------------------------------------------------------------
// sms_item_receipts
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const SmsItemReceipts = sequelize.define('sms_item_receipts', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        netsuiteIrId: { type: DataTypes.TEXT },
        poNumber: { type: DataTypes.TEXT, allowNull: false, references: { model: 'sms_pos', key: 'poNumber', deferrable: Deferrable.INITIALLY_DEFERRED } },
        receiptDate: { type: DataTypes.DATEONLY },
        source: { type: DataTypes.TEXT },
        matchedShipmentId: { type: DataTypes.TEXT, references: { model: 'sms_shipments', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        confirmedBy: { type: DataTypes.TEXT },
        confirmedAt: { type: DataTypes.DATE },
        netsuiteIrTranid: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'sms_item_receipts',
        indexes: [
            { unique: true, fields: ['netsuiteIrId'] },
        ],
    });

    SmsItemReceipts.associate = (models) => {
        SmsItemReceipts.belongsTo(models.SmsPos, { as: 'poNumber_ref', foreignKey: 'poNumber', targetKey: 'poNumber', constraints: false });
        SmsItemReceipts.belongsTo(models.SmsShipments, { as: 'matchedShipmentId_ref', foreignKey: 'matchedShipmentId', targetKey: 'id', constraints: false });
    };

    return SmsItemReceipts;
};
