// ---------------------------------------------------------------------------
// sms_po_lines
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
//
// ⚠️ NO PRIMARY KEY IN THE DATA. Sequelize requires one, and inventing an
// autoincrement `id` would add a column the table does not have, so `_seq`
// is the key: it is NOT NULL and unique by construction (assigned 0..n-1 on
// every whole-table write). See database/README.md for why these tables have no
// natural key yet.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const SmsPoLines = sequelize.define('sms_po_lines', {
        id: { type: DataTypes.TEXT },
        poNumber: { type: DataTypes.TEXT, allowNull: false, references: { model: 'sms_pos', key: 'poNumber', deferrable: Deferrable.INITIALLY_DEFERRED } },
        skuCode: { type: DataTypes.TEXT, references: { model: 'product_skus', key: 'skuCode', deferrable: Deferrable.INITIALLY_DEFERRED } },
        orderedQty: { type: DataTypes.INTEGER },
        unitPrice: { type: DataTypes.DECIMAL },
        netsuiteLineId: { type: DataTypes.TEXT },
        _seq: { type: DataTypes.BIGINT, allowNull: false, primaryKey: true },
    }, {
        tableName: 'sms_po_lines',
        indexes: [
            { unique: true, fields: ['poNumber', 'netsuiteLineId'] },
            { fields: ['poNumber', 'skuCode'] },
        ],
    });

    SmsPoLines.associate = (models) => {
        SmsPoLines.belongsTo(models.SmsPos, { as: 'poNumber_ref', foreignKey: 'poNumber', targetKey: 'poNumber', constraints: false });
        SmsPoLines.belongsTo(models.ProductSkus, { as: 'skuCode_ref', foreignKey: 'skuCode', targetKey: 'skuCode', constraints: false });
    };

    return SmsPoLines;
};
