// ---------------------------------------------------------------------------
// sms_packing_cartons
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const SmsPackingCartons = sequelize.define('sms_packing_cartons', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        shipmentId: { type: DataTypes.TEXT, allowNull: false, references: { model: 'sms_shipments', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        poNumber: { type: DataTypes.TEXT, allowNull: false, references: { model: 'sms_pos', key: 'poNumber', deferrable: Deferrable.INITIALLY_DEFERRED } },
        ctnNumber: { type: DataTypes.INTEGER },
        skuCode: { type: DataTypes.TEXT, references: { model: 'product_skus', key: 'skuCode', deferrable: Deferrable.INITIALLY_DEFERRED } },
        pcsPerCtn: { type: DataTypes.INTEGER },
        unitPrice: { type: DataTypes.DECIMAL },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'sms_packing_cartons',
        indexes: [
            { unique: true, fields: ['shipmentId', 'ctnNumber', 'skuCode'] },
        ],
    });

    SmsPackingCartons.associate = (models) => {
        SmsPackingCartons.belongsTo(models.SmsShipments, { as: 'shipmentId_ref', foreignKey: 'shipmentId', targetKey: 'id', constraints: false });
        SmsPackingCartons.belongsTo(models.SmsPos, { as: 'poNumber_ref', foreignKey: 'poNumber', targetKey: 'poNumber', constraints: false });
        SmsPackingCartons.belongsTo(models.ProductSkus, { as: 'skuCode_ref', foreignKey: 'skuCode', targetKey: 'skuCode', constraints: false });
    };

    return SmsPackingCartons;
};
