// ---------------------------------------------------------------------------
// sms_receipt_match_rejections
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const SmsReceiptMatchRejections = sequelize.define('sms_receipt_match_rejections', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        receiptId: { type: DataTypes.TEXT, allowNull: false, references: { model: 'sms_item_receipts', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        shipmentId: { type: DataTypes.TEXT, allowNull: false, references: { model: 'sms_shipments', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        rejectedBy: { type: DataTypes.TEXT },
        rejectedAt: { type: DataTypes.DATE },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'sms_receipt_match_rejections',
        indexes: [
            { unique: true, fields: ['receiptId', 'shipmentId'] },
        ],
    });

    SmsReceiptMatchRejections.associate = (models) => {
        SmsReceiptMatchRejections.belongsTo(models.SmsItemReceipts, { as: 'receiptId_ref', foreignKey: 'receiptId', targetKey: 'id', constraints: false });
        SmsReceiptMatchRejections.belongsTo(models.SmsShipments, { as: 'shipmentId_ref', foreignKey: 'shipmentId', targetKey: 'id', constraints: false });
    };

    return SmsReceiptMatchRejections;
};
