// ---------------------------------------------------------------------------
// sms_shipments
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const SmsShipments = sequelize.define('sms_shipments', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        courierId: { type: DataTypes.TEXT, allowNull: false },
        trackingNumber: { type: DataTypes.TEXT },
        shipDate: { type: DataTypes.DATEONLY },
        facilityId: { type: DataTypes.TEXT, references: { model: 'warehouse_facilities', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        manualStatusId: { type: DataTypes.TEXT, references: { model: 'statuses', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        createdBy: { type: DataTypes.TEXT },
        createdAt: { type: DataTypes.DATE },
        bookingId: { type: DataTypes.TEXT, references: { model: 'sms_bookings', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        customsEntryNumber: { type: DataTypes.TEXT },
        duty: { type: DataTypes.DECIMAL },
        freight: { type: DataTypes.DECIMAL },
        modeId: { type: DataTypes.TEXT, references: { model: 'modes', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'sms_shipments',
        indexes: [
            { unique: true, fields: ['trackingNumber'] },
        ],
    });

    SmsShipments.associate = (models) => {
        SmsShipments.belongsTo(models.Modes, { as: 'modeId_ref', foreignKey: 'modeId', targetKey: 'id', constraints: false });
        SmsShipments.belongsTo(models.WarehouseFacilities, { as: 'facilityId_ref', foreignKey: 'facilityId', targetKey: 'id', constraints: false });
        SmsShipments.belongsTo(models.Statuses, { as: 'manualStatusId_ref', foreignKey: 'manualStatusId', targetKey: 'id', constraints: false });
        SmsShipments.belongsTo(models.SmsBookings, { as: 'bookingId_ref', foreignKey: 'bookingId', targetKey: 'id', constraints: false });
    };

    return SmsShipments;
};
