// ---------------------------------------------------------------------------
// statuses
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const Statuses = sequelize.define('statuses', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        name: { type: DataTypes.TEXT, allowNull: false },
        module: { type: DataTypes.TEXT },
        category: { type: DataTypes.TEXT },
        color: { type: DataTypes.TEXT },
        sortOrder: { type: DataTypes.INTEGER },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'statuses',
        indexes: [
            { unique: true, fields: ['module', 'name'] },
        ],
    });

    return Statuses;
};
