// ---------------------------------------------------------------------------
// transit_time_standards
//
// GENERATED by database/generateModels.js. Re-running that script overwrites this
// file. After the initial generation this model is the AUTHORITY on the table:
// add a column here, not by editing backend/database/seed-data/.
// ---------------------------------------------------------------------------
'use strict';

const { Deferrable } = require('sequelize');

module.exports = (sequelize, DataTypes) => {
    const TransitTimeStandards = sequelize.define('transit_time_standards', {
        id: { type: DataTypes.TEXT, primaryKey: true },
        modeId: { type: DataTypes.TEXT, allowNull: false, references: { model: 'modes', key: 'id', deferrable: Deferrable.INITIALLY_DEFERRED } },
        segment: { type: DataTypes.TEXT, allowNull: false },
        days: { type: DataTypes.INTEGER, allowNull: false },
        _seq: { type: DataTypes.BIGINT, allowNull: false },
    }, {
        tableName: 'transit_time_standards',
        indexes: [
            { unique: true, fields: ['modeId', 'segment'] },
        ],
    });

    TransitTimeStandards.associate = (models) => {
        TransitTimeStandards.belongsTo(models.Modes, { as: 'modeId_ref', foreignKey: 'modeId', targetKey: 'id', constraints: false });
    };

    return TransitTimeStandards;
};
