// ---------------------------------------------------------------------------
// Emit models/*.js — ONE RUN, to hand authority over from the JSON files.
//
//   node database/generateModels.js            write models/
//   node database/generateModels.js --dry-run  report, write nothing
//
// This is a MIGRATION TOOL, not part of the running app and not something to
// re-run casually. Until now the schema was inferred from backend/database/seed-data/
// by db/buildSchema.js, which made a frozen snapshot of the data the definition
// of the database. This reads that inference ONE LAST TIME and freezes it into
// real model files. After this, models/ is the authority: a column is added
// by editing a model, not by editing JSON and re-inferring.
//
// Re-running it OVERWRITES hand-edits to the generated models. That is why the
// generated header says so in every file.
//
// WHY MODEL NAME == TABLE NAME. Sequelize's convention is a singular model name
// pluralised into a table name, and that convention cannot survive this schema:
// `notify_party` would be looked up as `notify_parties`, `sms_pos` and
// `statuses` are already ambiguous, and the table names are fixed by 193 call
// sites and by the data itself. So freezeTableName is on and the model is named
// for its table — a 1:1 mapping with no inflection anywhere to get wrong.
// ---------------------------------------------------------------------------
const fs = require('fs');
const path = require('path');

const SCHEMA_PATH = path.join(__dirname, 'schema.json');
// backend/models/ — the MVC models directory, beside controllers/ and routes/.
const OUT_DIR = path.join(__dirname, '..', 'models');
const DRY_RUN = process.argv.includes('--dry-run');

// Postgres type -> Sequelize DataType. The two marked ones do NOT round-trip on
// their own; database/modelStore.js decodes them back. See the probe results recorded
// in database/README.md.
const TYPE_MAP = {
    text: 'DataTypes.TEXT',
    integer: 'DataTypes.INTEGER',
    numeric: 'DataTypes.DECIMAL',      // ⚠️ Sequelize returns a STRING — decoded to Number
    boolean: 'DataTypes.BOOLEAN',
    date: 'DataTypes.DATEONLY',        // returns 'YYYY-MM-DD', which is what we want
    timestamptz: 'DataTypes.DATE',     // ⚠️ Sequelize returns a Date — decoded to ISO string
    json: 'DataTypes.JSON',
};

/** `mainline_po_legs` -> `MainlinePoLegs`. No inflection — see the header. */
function pascal(name) {
    return name.split(/[^a-zA-Z0-9]+/).filter(Boolean)
        .map((w) => w[0].toUpperCase() + w.slice(1))
        .join('');
}

/**
 * Kept for re-runs against an older schema.json. The live columns are ALREADY
 * camelCase (renamed in the database 2026-09-21), so this is now a no-op on
 * every name and no `field:` mapping is emitted — the attribute IS the column.
 *
 * ⚠️ There is deliberately no reverse of this function anywhere. Four columns in
 * `nri_order_master` (`orderNo`, `custCode`, `custName`, `orderType`) were
 * already camelCase before the rename, so a naive snake() would "restore" them
 * to `order_no` and friends — columns that have never existed.
 */
function camel(name) {
    return name.replace(/_([a-z0-9])/g, (_, c) => c.toUpperCase());
}

/**
 * `polPortId` -> `polPort`; `bookingId` -> `booking`.
 *
 * Sequelize refuses an association whose alias equals one of the model's own
 * attributes, and several FK columns here do NOT end in `_id` — `landed_costs`
 * has a column literally called `postedBy` that is also its FK to `users`, so
 * the stripped alias would be the column name. `taken` also carries the aliases
 * already used on this table, because two FKs can strip to the same word.
 */
function aliasFor(column, columnNames, taken) {
    const base = column.replace(/_id$/, '');
    let alias = base;
    let n = 2;
    while (columnNames.has(alias) || taken.has(alias)) {
        alias = alias === base ? `${base}_ref` : `${base}_ref${n++}`;
    }
    taken.add(alias);
    return alias;
}

function q(s) {
    return `'${String(s).replace(/'/g, "\\'")}'`;
}

function buildModelFile(table, schema, realFks) {
    const pk = table.primaryKey && table.primaryKey.length ? table.primaryKey : null;
    const pkSet = new Set(pk || []);
    const lines = [];

    lines.push('// ---------------------------------------------------------------------------');
    lines.push(`// ${table.name}`);
    lines.push('//');
    lines.push('// GENERATED by database/generateModels.js. Re-running that script overwrites this');
    lines.push('// file. After the initial generation this model is the AUTHORITY on the table:');
    lines.push('// add a column here, not by editing backend/database/seed-data/.');
    if (!pk) {
        lines.push('//');
        lines.push('// ⚠️ NO PRIMARY KEY IN THE DATA. Sequelize requires one, and inventing an');
        lines.push('// autoincrement `id` would add a column the table does not have, so `_seq`');
        lines.push('// is the key: it is NOT NULL and unique by construction (assigned 0..n-1 on');
        lines.push('// every whole-table write). See database/README.md for why these tables have no');
        lines.push('// natural key yet.');
    }
    lines.push('// ---------------------------------------------------------------------------');
    lines.push("'use strict';");
    lines.push('');
    lines.push("const { Deferrable } = require('sequelize');");
    lines.push('');
    lines.push('module.exports = (sequelize, DataTypes) => {');
    lines.push(`    const ${pascal(table.name)} = sequelize.define(${q(table.name)}, {`);

    // Two columns collapsing to one attribute would silently drop a field, so
    // prove it cannot happen rather than assume it. (0 across all 380 columns.)
    const byAttr = new Map();
    for (const col of table.columns) {
        const attr = camel(col.name);
        if (byAttr.has(attr)) {
            throw new Error(
                `${table.name}: columns "${byAttr.get(attr)}" and "${col.name}" both camelCase to "${attr}"`,
            );
        }
        byAttr.set(attr, col.name);
    }

    for (const col of table.columns) {
        const type = TYPE_MAP[col.type];
        if (!type) throw new Error(`no DataType mapped for ${table.name}.${col.name} (${col.type})`);
        const attr = camel(col.name);
        const opts = [`type: ${type}`];
        // Only emitted if a column is somehow not already camelCase. Since the
        // 2026-09-21 rename the attribute IS the column, so in practice no
        // `field:` mapping is written at all.
        if (attr !== col.name) opts.push(`field: ${q(col.name)}`);
        if (pkSet.has(col.name)) opts.push('primaryKey: true');
        if (col.notNull) opts.push('allowNull: false');

        // A real foreign key — one the live data can actually satisfy. The
        // others are declared as associations only (constraints: false), since
        // the rows violate them; database/README.md lists which and why.
        //
        // ⚠️ DEFERRABLE INITIALLY DEFERRED IS LOAD-BEARING. Every write is a
        // whole-table replace (DELETE-all + INSERT-all), so any write to a
        // parent momentarily removes every row its children point at. Checked
        // at COMMIT, that is fine; checked per statement, every write fails.
        //
        // ⚠️ `deferrable` MUST SIT INSIDE `references`. As a sibling of it
        // Sequelize accepts the key silently and ignores it — measured: all 79
        // foreign keys came out condeferrable=false, and seeding then failed on
        // the first child table whose parent had not been loaded yet.
        const fk = realFks.get(`${table.name}|${col.name}`);
        if (fk) {
            // `key` is the COLUMN in the target table — Sequelize passes it into
            // the DDL, so it stays snake_case while `targetKey` on the
            // association below is the target's ATTRIBUTE.
            opts.push(`references: { model: ${q(fk.refTable)}, key: ${q(fk.refColumn)}, ` +
                'deferrable: Deferrable.INITIALLY_DEFERRED }');
        }
        lines.push(`        ${attr}: { ${opts.join(', ')} },`);
    }

    // _seq is not in schema.json's column list — buildSchema adds it in the DDL.
    // It is declared here so the model matches the real table, and the store
    // strips it from everything handed back to a caller.
    const seqOpts = ['type: DataTypes.BIGINT', 'allowNull: false'];
    if (!pk) seqOpts.push('primaryKey: true');
    lines.push(`        _seq: { ${seqOpts.join(', ')} },`);

    lines.push('    }, {');
    lines.push(`        tableName: ${q(table.name)},`);

    const indexes = [];
    for (const u of table.uniques || []) {
        const entry = `{ unique: true, fields: [${u.columns.map(q).join(', ')}] }`;
        indexes.push(u.nullsNotDistinct
            ? `${entry},   // NULLS NOT DISTINCT in the DDL — Sequelize cannot express it`
            : `${entry},`);
    }
    // A plain index in schema.json is just an array of column names.
    for (const i of table.indexes || []) {
        const cols = Array.isArray(i) ? i : i.columns;
        indexes.push(`{ fields: [${cols.map(q).join(', ')}] },`);
    }
    if (indexes.length) {
        lines.push('        indexes: [');
        indexes.forEach((i) => lines.push(`            ${i}`));
        lines.push('        ],');
    }
    lines.push('    });');
    lines.push('');

    // Associations are declared in a static so index.js can wire them only once
    // every model exists — a belongsTo cannot name a model that is not defined.
    const refs = (table.refs || []).filter((r) => schema.tables.some((t) => t.name === r.table));
    if (refs.length) {
        lines.push(`    ${pascal(table.name)}.associate = (models) => {`);
        // Aliases are checked against the ATTRIBUTE names, since that is what
        // Sequelize compares them to.
        const attrNames = new Set(table.columns.map((c) => camel(c.name)).concat('_seq'));
        const taken = new Set();
        for (const r of refs) {
            const target = pascal(r.table);
            const targetTable = schema.tables.find((t) => t.name === r.table);
            const targetCol = targetTable && targetTable.columns.find((c) => c.name === r.refColumn);
            // foreignKey and targetKey are ATTRIBUTES, not columns — Sequelize
            // resolves them to columns through each model's `field`.
            const fkAttr = camel(r.column);
            const targetAttr = targetCol ? camel(targetCol.name) : camel(r.refColumn);
            const alias = aliasFor(fkAttr, attrNames, taken);
            lines.push(`        ${pascal(table.name)}.belongsTo(models.${target}, ` +
                `{ as: ${q(alias)}, foreignKey: ${q(fkAttr)}, targetKey: ${q(targetAttr)}, constraints: false });`);
        }
        lines.push('    };');
        lines.push('');
    }

    lines.push(`    return ${pascal(table.name)};`);
    lines.push('};');
    lines.push('');
    return lines.join('\n');
}

function buildIndexFile(schema) {
    const L = [];
    L.push('// ---------------------------------------------------------------------------');
    L.push('// The model registry.');
    L.push('//');
    L.push('// Loads every model in this directory onto the one Sequelize instance, wires');
    L.push('// the associations, and exposes the two lookups the rest of the backend needs:');
    L.push('//');
    L.push('//   models[tableName]      the Sequelize model (also keyed PascalCase)');
    L.push('//');
    L.push('// Each model carries .read() / .write(rows) for whole-table access — see');
    L.push('// database/modelStore.js. The filename->table registry that used to live here');
    L.push('// is gone: seed files are named after their table, so no mapping is needed.');
    L.push('// ---------------------------------------------------------------------------');
    L.push("'use strict';");
    L.push('');
    L.push("const fs = require('fs');");
    L.push("const path = require('path');");
    L.push("const { DataTypes } = require('sequelize');");
    L.push("const { sequelize, Sequelize } = require('../database/sequelize');");
    L.push('');
    L.push('// Keyed TWICE on purpose: by table name (`models.mainline_shipments`), which');
    L.push('// is what the file registry and the BaseModel facade resolve to, and by the');
    L.push("// PascalCase model name (`models.MainlineShipments`), which is what a model's");
    L.push('// own associate() names. One registry, two spellings of the same object.');
    L.push('const models = {};');
    L.push('');
    L.push("/** `mainline_po_legs` -> `MainlinePoLegs`. */");
    L.push('function pascal(name) {');
    L.push('    return name.split(/[^a-zA-Z0-9]+/).filter(Boolean)');
    L.push('        .map((w) => w[0].toUpperCase() + w.slice(1))');
    L.push("        .join('');");
    L.push('}');
    L.push('');
    L.push('// ⚠️ `*Model.js` is SKIPPED. This directory also holds the legacy table');
    L.push('// facades (BaseModel.js, UserModel.js, MasterDataModel.js …), which export a');
    L.push('// class or a BaseModel instance rather than a (sequelize, DataTypes) factory.');
    L.push('// BaseModel is itself a class — and a class IS typeof "function" — so a');
    L.push('// duck-typed check would call it without `new` and throw. The name rule is');
    L.push('// the reliable one.');
    L.push('for (const file of fs.readdirSync(__dirname)) {');
    L.push("    if (file === 'index.js' || !file.endsWith('.js')) continue;");
    L.push("    if (file.endsWith('Model.js')) continue;");
    L.push('    const define = require(path.join(__dirname, file));');
    L.push('    const model = define(sequelize, DataTypes);');
    L.push('    models[model.name] = model;');
    L.push('    models[pascal(model.name)] = model;');
    L.push('}');
    L.push('');
    L.push('// Second pass: every model exists now, so a belongsTo can name its target.');
    L.push('// Deduplicated because the registry holds each model under two keys, and');
    L.push('// associating twice would define every relation twice.');
    L.push('for (const model of new Set(Object.values(models))) {');
    L.push("    if (typeof model.associate === 'function') model.associate(models);");
    L.push('');
    L.push('    // Whole-table read/write, the shape ~190 call sites use:');
    L.push('    //   const rows = await models.po_orders.read();');
    L.push('    //   await models.po_orders.write(next);');
    L.push('    // This is what replaced models/BaseModel.js. Semantics are unchanged —');
    L.push('    // write() REPLACES the table, so a row missing from the array is deleted.');
    L.push('    //');
    L.push('    // ⚠️ database/modelStore is required lazily INSIDE the functions. It requires');
    L.push('    // this file, so requiring it at the top would be a cycle and one of the');
    L.push("    // two would see a half-built module. Sequelize's Model has no `read` or");
    L.push('    // `write` static, so neither name shadows anything.');
    L.push('    model.read = function read() {');
    L.push("        return require('../database/modelStore').readAll(this);");
    L.push('    };');
    L.push('    model.write = function write(rows) {');
    L.push("        return require('../database/modelStore').replaceAll(this, rows);");
    L.push('    };');
    L.push('}');
    L.push('');
    L.push('module.exports = { sequelize, Sequelize, models };');
    L.push('');
    return L.join('\n');
}

function main() {
    const schema = JSON.parse(fs.readFileSync(SCHEMA_PATH, 'utf8'));
    const files = [];

    // Only the foreign keys the live data can satisfy get a DDL constraint. The
    // rest stay associations without one — see the note in buildModelFile.
    const realFks = new Map();
    for (const fk of schema.foreignKeys) {
        realFks.set(`${fk.table}|${fk.column}`, fk);
    }

    for (const table of schema.tables) {
        files.push({ name: `${pascal(table.name)}.js`, body: buildModelFile(table, schema, realFks) });
    }
    files.push({ name: 'index.js', body: buildIndexFile(schema) });

    // A name collision would silently drop a model, so prove there is none.
    const seen = new Map();
    for (const f of files) {
        if (seen.has(f.name)) throw new Error(`model file collision: ${f.name}`);
        seen.set(f.name, true);
    }

    console.log(`${schema.tables.length} tables -> ${files.length} files in models/`);
    console.log(`${schema.foreignKeys.length} foreign keys -> belongsTo associations`);
    const noPk = schema.tables.filter((t) => !t.primaryKey || !t.primaryKey.length);
    if (noPk.length) {
        console.log(`\n${noPk.length} tables have no primary key in the data; keyed on _seq:`);
        noPk.forEach((t) => console.log(`  ${t.name} (${t.rowCount.toLocaleString()} rows)`));
    }

    if (DRY_RUN) {
        console.log('\n--dry-run: nothing written.');
        return;
    }

    fs.mkdirSync(OUT_DIR, { recursive: true });
    for (const f of files) {
        fs.writeFileSync(path.join(OUT_DIR, f.name), f.body);
    }
    console.log(`\nwrote ${files.length} files.`);
}

main();
